pipeline {
    agent{
         label 'linux'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Pranay12e/simple-javaapp.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }

    post {
        success {
            echo 'Build and tests passed successfully!'
        }
        failure {
            echo 'Build or tests failed.'
        }
    }
}

