pipeline {
    agent any
    tools {
        maven 'Maven' 
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Pranay12e/simple-javaapp.git'
            }
        }

       stage('Build') {
            steps {
                bat 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }
    }

    post {
        success {
            echo 'Build and tests passed successfully!'
        }
        failure {
            echo 'Build or tests failed.'
        }
    }
}

